apiVersion: v1
kind: Secret
metadata:
  name: backend
  namespace: {{ .Release.Namespace | quote }}
stringData:
  DJANGO_SUPERUSER_EMAIL: {{ .Values.djangoSuperUserEmail }}
  DJANGO_SUPERUSER_PASSWORD: {{ .Values.djangoSuperUserPass }}
  DJANGO_SECRET_KEY: {{ .Values.djangoSecretKey }}
  OIDC_RP_CLIENT_ID: {{ .Values.oidc.clientId }}
  OIDC_RP_CLIENT_SECRET: {{ .Values.oidc.clientSecret }}
{{- if .Values.resourceServer }}
  OIDC_RS_CLIENT_ID: {{ .Values.resourceServer.clientId }}
  OIDC_RS_CLIENT_SECRET: {{ .Values.resourceServer.clientSecret }}
  OIDC_RS_PRIVATE_KEY_STR: |
{{ .Values.resourceServer.privateKey | indent 4 }}
{{- end }}
{{- if .Values.mail_provisionning_api_credentials }}
  MAIL_PROVISIONING_API_CREDENTIALS: {{ .Values.mail_provisionning_api_credentials }}
{{- end }}
