#
# Your crowdin's credentials
#
api_token_env: CROWDIN_API_TOKEN
project_id_env: CROWDIN_PROJECT_ID
base_path_env: CROWDIN_BASE_PATH

#
# Choose file structure in crowdin
# e.g. true or false
#
preserve_hierarchy: true

#
# Files configuration
#
files:
  [
    {
      source: "/backend/locale/django.pot",
      dest: "/backend.pot",
      translation: "/backend/locale/%locale_with_underscore%/LC_MESSAGES/django.po",
    },
    {
      source: "/frontend/packages/i18n/locales/desk/translations-crowdin.json",
      dest: "/desk.json",
      translation: "/frontend/packages/i18n/locales/desk/%two_letters_code%/translations.json",
      skip_untranslated_strings: true,
    },
  ]
