image:
  repository: localhost:5001/people-backend
  pullPolicy: Always
  tag: "latest"

backend:
  envVars:
    DJANGO_CORS_ALLOWED_ORIGINS: http://desk.127.0.0.1.nip.io,https://desk.127.0.0.1.nip.io
    DJANGO_CONFIGURATION: Production
    DJANGO_ALLOWED_HOSTS: "*"
    DJANGO_SECRET_KEY: "ThisIsAnExampleKeyForDevPurposeOnly"
    DJANGO_SETTINGS_MODULE: people.settings
    DJANGO_SUPERUSER_PASSWORD: admin
    DJANGO_EMAIL_HOST: "mailcatcher"
    DJANGO_EMAIL_PORT: 1025
    OIDC_OP_JWKS_ENDPOINT: https://fca.integ01.dev-agentconnect.fr/api/v2/jwks
    OIDC_OP_AUTHORIZATION_ENDPOINT: https://fca.integ01.dev-agentconnect.fr/api/v2/authorize
    OIDC_OP_TOKEN_ENDPOINT: https://fca.integ01.dev-agentconnect.fr/api/v2/token
    OIDC_OP_USER_ENDPOINT: https://fca.integ01.dev-agentconnect.fr/api/v2/userinfo
    OIDC_RP_CLIENT_ID: "ThisIsAnExampleIdForDevPurposeOnly"
    OIDC_RP_CLIENT_SECRET: "ThisIsAnExampleKeyForDevPurposeOnly"
    OIDC_RP_SIGN_ALGO: RS256
    OIDC_RP_SCOPES: "openid email"
    OIDC_REDIRECT_ALLOWED_HOSTS: https://desk.127.0.0.1.nip.io
    OIDC_AUTH_REQUEST_EXTRA_PARAMS: "{'acr_values': 'eidas1'}"
    LOGIN_REDIRECT_URL: https://desk.127.0.0.1.nip.io
    LOGIN_REDIRECT_URL_FAILURE: https://desk.127.0.0.1.nip.io
    LOGOUT_REDIRECT_URL: https://desk.127.0.0.1.nip.io/login
    DB_HOST: postgres-postgresql
    DB_NAME: people
    DB_USER: dinum
    DB_PASSWORD: pass
    DB_PORT: 5432
    POSTGRES_DB: people
    POSTGRES_USER: dinum
    POSTGRES_PASSWORD: pass

frontend:
  image:
    repository: localhost:5001/people-frontend
    pullPolicy: Always
    tag: "latest"

ingress:
  host: desk.127.0.0.1.nip.io


