apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dimail
  labels:
    app: dimail
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: dimail.127.0.0.1.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dimail
                port:
                  number: 8000
