# Generated by Django 5.0.3 on 2024-04-17 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailbox_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maildomainaccess',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='mailbox_manager.maildomain'),
        ),
    ]
