# Generated by Django 5.0.4 on 2024-06-03 08:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailbox_manager', '0002_alter_maildomainaccess_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailDomainWebhook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated at')),
                ('url', models.URLField(verbose_name='url')),
                ('secret', models.CharField(blank=True, max_length=255, null=True, verbose_name='secret')),
                ('status', models.CharField(choices=[('failure', 'Failure'), ('pending', 'Pending'), ('success', 'Success')], default='pending', max_length=10)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='mailbox_manager.maildomain')),
            ],
            options={
                'verbose_name': 'MailDomain webhook',
                'verbose_name_plural': 'MailDomain webhooks',
                'db_table': 'people_maildomain_webhook',
            },
        ),
    ]
