# Generated by Django 5.0.6 on 2024-06-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailbox_manager', '0002_alter_maildomainaccess_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='maildomain',
            name='slug',
            field=models.SlugField(blank=True, max_length=80),
        ),
    ]
