# Generated by Django 5.0.6 on 2024-06-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailbox_manager', '0004_maildomain_fill_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maildomain',
            name='slug',
            field=models.SlugField(max_length=80, unique=True),
        ),
    ]
