# Generated by Django 5.0.6 on 2024-07-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailbox_manager', '0005_alter_maildomain_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='maildomain',
            name='secret',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='secret'),
        ),
    ]
