# Generated by Django 5.0.6 on 2024-08-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailbox_manager', '0007_alter_maildomainaccess_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbox',
            name='first_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='last_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
