# Generated by Django 5.0.6 on 2024-08-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailbox_manager', '0009_fill_mailbox_first_name_mailbox_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailbox',
            name='first_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mailbox',
            name='last_name',
            field=models.CharField(max_length=200),
        ),
    ]
