# Generated by Django 5.1 on 2024-08-30 10:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailbox_manager', '0011_maildomain_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailbox',
            name='local_part',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z0-9_.-]+$')], verbose_name='local_part'),
        ),
    ]
