# Generated by Django 5.1.3 on 2024-11-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailbox_manager', '0013_remove_maildomain_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbox',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('enabled', 'Enabled'), ('failed', 'Failed'), ('disabled', 'Disabled')], default='pending', max_length=20),
        ),
    ]
