# Generated by Django 5.1.2 on 2024-11-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='slug',
            field=models.SlugField(max_length=100, null=True),
        ),
    ]
