# Generated by Django 5.1.2 on 2024-11-07 16:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_team_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated at')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='name')),
                ('audience_id', models.CharField(db_index=True, max_length=256, unique=True, verbose_name='audience id')),
            ],
            options={
                'verbose_name': 'service provider',
                'verbose_name_plural': 'service providers',
                'db_table': 'people_service_provider',
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='service_providers',
            field=models.ManyToManyField(blank=True, related_name='organizations', to='core.serviceprovider'),
        ),
        migrations.AddField(
            model_name='team',
            name='service_providers',
            field=models.ManyToManyField(blank=True, related_name='teams', to='core.serviceprovider'),
        ),
    ]
