# Generated by Django 5.1.3 on 2024-11-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_serviceprovider'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='full_name',
            field=models.CharField(default='-', max_length=150, verbose_name='full name'),
            preserve_default=False,
        ),
    ]
