# Generated by Django 5.1.3 on 2024-11-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_serviceprovider'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contact',
            name='base_owner_constraint',
        ),
        migrations.RemoveConstraint(
            model_name='contact',
            name='base_not_self',
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices="(('en-us', 'English'), ('fr-fr', 'French'))", default='en-us', help_text='The language in which the user wants to see the interface.', max_length=10, verbose_name='language'),
        ),
        migrations.RemoveField(
            model_name='contact',
            name='base',
        ),
    ]
