# Generated by Django 5.1.3 on 2024-11-26 13:55

from django.db import migrations, models

from treebeard.mp_tree import MP_Node


def update_team_paths(apps, schema_editor):
    Team = apps.get_model("core", "Team")
    alphabet = MP_Node.alphabet
    steplen = MP_Node.steplen

    # for default values, this resolves to: "{:04d}"
    path_format = f"{{:{alphabet[0]}{steplen}d}}"

    nodes = Team.objects.all().order_by("created_at")
    for i, node in enumerate(nodes, 1):
        node.path = path_format.format(i)

    if nodes:
        Team.objects.bulk_update(nodes, ["path"])

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_change_user_profile_to_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='depth',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='numchild',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='path',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.RunPython(update_team_paths, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="team",
            name="path",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
