# Generated by Django 5.1.3 on 2024-12-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_change_user_profile_to_contact'),
    ]

    operations = [
        # From 100ms to 78ms for 5 000 contacts on my computer
        # This is not a big improvement and may need further investigation
        migrations.RunSQL(
           "CREATE INDEX json_field_index_emails_value ON people_contact USING GIN ((data->'emails'->'value') jsonb_path_ops);"
        )
    ]
