name: Helmfile lint
run-name: Helmfile lint

on:
  pull_request:
    branches:
      - 'main'

jobs:
  helmfile-lint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/helmfile/helmfile:latest
    steps:
      -
        uses: numerique-gouv/action-helmfile-lint@main
        with:
          app-id: ${{ secrets.APP_ID }}
          age-key: ${{ secrets.SOPS_PRIVATE }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          helmfile-src: "src/helm"
          repositories: "people,secrets"
